name: hiphop
description: "Hiphop Muscial App"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get:
  get_storage: ^2.1.1
  smooth_page_indicator: ^1.1.0
  image_picker: ^1.0.7
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter_facebook_auth: ^6.1.1
  flutter_svg: ^2.0.10+1
  persistent_bottom_nav_bar:
  flutter_screenutil: ^5.9.0
  share_plus: ^8.0.2
  audioplayers: ^5.2.1
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  fluentui_system_icons: ^1.1.225
  flutter_launcher_icons: ^0.13.1
  email_validator: ^2.1.17
  fluttertoast: ^8.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
     - assets/images/
     - assets/music/
     - assets/images/artist_images/
  #   - images/a_dot_ham.jpeg

  fonts:
   - family: Poppins
     fonts:
       - asset: assets/fonts/Poppins/Poppins-Regular.ttf
         weight: 400

       - asset: assets/fonts/Poppins/Poppins-Bold.ttf
         weight: 700

       - asset: assets/fonts/Poppins/Poppins-Medium.ttf
         weight: 500

       - asset: assets/fonts/Poppins/Poppins-Black.ttf
         weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#ffffff"
  remove_alpha_ios: true
  image_path: assets/images/app_logo_dark.png